name: shorturlapi
services:
  shortener:
    build: shortener
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - database

  redirector:
    build: redirector
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - database

  database:
    image: "postgres:16-alpine"
    restart: always
    volumes:
      - "database:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "apiuser"
      POSTGRES_PASSWORD: "apipassword"
      POSTGRES_DB: "apidb"

  cass1:
    image: cassandra:5.0
    container_name: cass1
    hostname: cass1
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    ports:
      - "9042:9042"
    volumes:
      - cass1-data:/var/lib/cassandra
    environment: &environment
        CASSANDRA_SEEDS: "cass1,cass2"
        CASSANDRA_CLUSTER_NAME: SolarSystem
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128

  cass2:
    image: cassandra:5.0
    container_name: cass2
    hostname: cass2
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    ports:
      - "9043:9042"
    volumes:
      - cass2-data:/var/lib/cassandra
    environment: *environment
    depends_on:
      cass1:
        condition: service_healthy

  cass3:
    image: cassandra:5.0
    container_name: cass3
    hostname: cass3
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    ports:
      - "9044:9042"
    volumes:
      - cass3-data:/var/lib/cassandra
    environment: *environment
    depends_on:
      cass2:
        condition: service_healthy

volumes:
  database:
  cass1-data:
  cass2-data:
  cass3-data:
  