name: shorturlapi
services:
  shortener:
    build: shortener
    restart: always
    ports:
      - "8081:8080"
    networks:
      default:
        ipv4_address: "172.22.0.10"
    depends_on:
      cass1:
        condition: service_healthy

  redirector:
    build: redirector
    restart: always
    ports:
      - "8082:8080"
    networks:
      default:
        ipv4_address: "172.22.0.20"
    depends_on:
      cass1:
        condition: service_healthy

  cass1:
    image: cassandra:5.0
    container_name: cass1
    hostname: cass1
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    volumes:
      - cass1-data:/var/lib/cassandra
    environment: &environment
        CASSANDRA_SEEDS: "cass1,cass2"
        CASSANDRA_CLUSTER_NAME: SolarSystem
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128
    networks:
      default:
        ipv4_address: "172.22.0.30"

  cass2:
    image: cassandra:5.0
    container_name: cass2
    hostname: cass2
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    volumes:
      - cass2-data:/var/lib/cassandra
    environment: *environment
    depends_on:
      cass1:
        condition: service_healthy
    networks:
      default:
        ipv4_address: "172.22.0.31"

  cass3:
    image: cassandra:5.0
    container_name: cass3
    hostname: cass3
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    volumes:
      - cass3-data:/var/lib/cassandra
    environment: *environment
    depends_on:
      cass2:
        condition: service_healthy
    networks:
      default:
        ipv4_address: "172.22.0.32"

volumes:
  cass1-data:
  cass2-data:
  cass3-data:
  
networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.22.0.0/24
         gateway: 172.22.0.1
