name: shorturlapi
services:
  shortener:
    build: shortener
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - database

  redirector:
    build: redirector
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - database

  database:
    image: "postgres:16-alpine"
    restart: always
    volumes:
      - "database:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "apiuser"
      POSTGRES_PASSWORD: "apipassword"
      POSTGRES_DB: "apidb"

  cassandra1:
    image: cassandra:5.0
    container_name: cassandra1
    hostname: cassandra1
    volumes:
      - "cassandra1:/var/lib/cassandra"
    environment: &environment
        CASSANDRA_SEEDS: "cassandra1,cassandra2"
        CASSANDRA_CLUSTER_NAME: MyTestCluster
        CASSANDRA_DC: DC1
        CASSANDRA_RACK: RACK1
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 10

  cassandra2:
    image: cassandra:5.0
    container_name: cassandra2
    hostname: cassandra2
    volumes:
      - "cassandra2:/var/lib/cassandra"
    environment: *environment
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      cassandra1:
        condition: service_healthy

  cassandra3:
    image: cassandra:5.0
    container_name: cassandra3
    hostname: cassandra3
    volumes:
      - "cassandra3:/var/lib/cassandra"
    environment: *environment
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      cassandra2:
        condition: service_healthy

volumes:
  database:
  cassandra1:
  cassandra2:
  cassandra3:
