name: shorturlapi
services:
  shortener:
    build: shortener
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - database

  redirector:
    build: redirector
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - database

  database:
    image: "postgres:16-alpine"
    restart: always
    volumes:
      - "database:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "apiuser"
      POSTGRES_PASSWORD: "apipassword"
      POSTGRES_DB: "apidb"

volumes:
  database:
